pipeline:
    documentation:
        image: nextcloudci/documentation:documentation-5
        commands:
            - npm install svgexport -g
            - pip2 install -r requirements.txt
            - make all
branches: [ master, stable* ]
