pipeline:
    image: nextcloudci/documentation:1.0.11
    commands:
        - (cd user_manual && make html-all)
        - (cd admin_manual && make html-all)
        - (cd developer_manual && make html-all)
