pipeline:
    documentation:
        image: nextcloudci/documentation:1.0.11
        commands:
            - (cd user_manual && make html-all)
            - (cd admin_manual && make html-all)
            - (cd developer_manual && make html-all)
            - (cd user_manual_de && make html-all)
