kind: pipeline
name: documentation

steps:
- name: documentation
  image: nextcloudci/documentation:documentation-9
  commands:
    - npm install svgexport@0.3.2 -g
    - pip2 install -r requirements.txt
    - make all

trigger:
  branch:
  - master
  - stable*
  event:
  - pull_request
  - push
